- docs/AboutUs.md
> Update Shiqi's AboutUs Page

- docs/AboutUs.md
> Update Ewen's Aboutus

- docs/AboutUs.md
> Update Derrick's AboutUs Page

- README.md
- docs/index.md
> Update github status badge

- docs/DeveloperGuide.md
> Update Use Cases

- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/model/person/Person.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
> Include default tag pending

- src/main/java/seedu/address/logic/commands/ViewStatusCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/ViewStatusCommandParser.java
- src/test/java/seedu/address/logic/commands/ViewStatusCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/ViewStatusCommandParserTest.java
> Add "view" command and relevant tests

- docs/DevOps.md
- docs/Documentation.md
- docs/Logging.md
- docs/UserGuide.md
- docs/index.md
- src/main/java/seedu/address/logic/commands/HireCommand.java
- src/main/java/seedu/address/logic/commands/RejectCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
- src/main/java/seedu/address/logic/parser/HireCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/logic/parser/RejectCommandParser.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/person/Job.java
- src/main/java/seedu/address/model/person/Name.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/HireCommandTest.java
- src/test/java/seedu/address/logic/commands/RejectCommandTest.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
- src/test/java/seedu/address/logic/parser/HireCommandParserTest.java
- src/test/java/seedu/address/logic/parser/RejectCommandParserTest.java
- src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
Closes #77 
Closes #76 
Closes #58
> Mark status

- src/main/java/seedu/address/model/person/Job.java
- src/main/java/seedu/address/model/person/Name.java
- src/main/java/seedu/address/model/person/Person.java
- src/test/java/seedu/address/model/person/JobTest.java
- src/test/java/seedu/address/model/person/NameTest.java
> Make view command case insensitive

- src/main/java/seedu/address/model/ModelManager.java
- src/test/java/seedu/address/model/ModelManagerTest.java
> Make hire and reject commands case insensitive

- docs/UserGuide.md
> Update User Guide to include new features

- build.gradle
- src/main/java/seedu/address/MainApp.java
- src/test/java/seedu/address/commons/core/VersionTest.java
> Update version to v1.3

- docs/UserGuide.md
> Update Add Command in User Guide

- docs/UserGuide.md
> Refine user guide

- src/main/resources/view/DarkTheme.css
- src/main/resources/view/PersonListCard.fxml
> Improve UI

- src/main/java/seedu/address/logic/commands/HireCommand.java
- src/main/java/seedu/address/logic/commands/RejectCommand.java
> Fix hire/reject command displays name in upper case

- src/main/java/seedu/address/MainApp.java
- src/test/java/seedu/address/commons/core/VersionTest.java
> Update MainApp version

- docs/diagrams/BetterModelClassDiagram.puml
- docs/diagrams/LogicClassDiagram.puml
- docs/diagrams/ModelClassDiagram.puml
> Update UML diagrams to include Skill and Interview Score

- src/main/java/seedu/address/logic/Logic.java
- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/logic/commands/SortCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/SortCommandParser.java
- src/main/java/seedu/address/logic/parser/exceptions/ParseException.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/person/InterviewScore.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/PersonListPanel.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/SortCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
- src/test/java/seedu/address/model/ModelManagerTest.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
> Add SortCommand

- docs/UserGuide.md
> Update user guide with new commands

- docs/SettingUp.md
- docs/_markbind/layouts/default.md
> Update defaults in project website

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/ClearCommand.java
- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/ExitCommand.java
- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/logic/commands/HireCommand.java
- src/main/java/seedu/address/logic/commands/ListCommand.java
- src/main/java/seedu/address/logic/commands/RejectCommand.java
- src/main/java/seedu/address/logic/commands/SortCommand.java
- src/main/java/seedu/address/logic/commands/ViewStatusCommand.java
- src/main/java/seedu/address/model/person/Email.java
- src/main/java/seedu/address/model/person/InterviewScore.java
- src/main/java/seedu/address/model/person/Name.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/person/Phone.java
- src/test/java/seedu/address/logic/commands/SortCommandTest.java
> Change UI messages to refer to HiredFiredPro

- src/main/java/seedu/hiredfiredpro/model/person/Job.java
- src/main/java/seedu/hiredfiredpro/model/person/Name.java
- src/main/java/seedu/hiredfiredpro/model/person/Person.java
- src/main/resources/view/HelpWindow.fxml
- src/test/java/seedu/hiredfiredpro/logic/commands/CommandTestUtil.java
- src/test/java/seedu/hiredfiredpro/model/person/JobTest.java
- src/test/java/seedu/hiredfiredpro/model/person/NameTest.java
- src/test/java/seedu/hiredfiredpro/model/person/PersonTest.java
> Fix definition of duplicate persons

- src/main/java/seedu/hiredfiredpro/logic/commands/EditCommand.java
- src/test/java/seedu/hiredfiredpro/logic/commands/EditCommandTest.java
> Fix empty edit tag changing edited person to pending
